---
title: "Resumo dos projetos"
author: "Nome do Aluno"
date: "5 de abril de 2018"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Essa página apresenta um resumo dos projetos realizado na disciplina **"Análise de Dados e Introdução à Machine Learning"**.

***

## Projeto 1

* Título: Análise Exploratória de Dados

### Relatório do Projeto

Link no [meu Github](<https://lucasfranz.github.io/MLRTemplate/>) *Pages*: [Projeto 1](projetos/)

***

## Projeto 2

* Título: Regressão linear - Preço dos imóveis

### Relatório do Projeto

Link no [meu Github](<https://lucasfranz.github.io/MLRTemplate/>) *Pages*: [Projeto 2](projetos/Trabalho_2 Regressão Preço Imóveis.html)


## Projeto 3

* Título: Regressão linear - Estudo de Caso BluSky

### Relatório do Projeto

Link no [meu Github](<https://lucasfranz.github.io/MLRTemplate/>) *Pages*: [Projeto 3](projetos/trabalho_3_-_Estudo_de_caso_BlueSky.html)

## Projeto 4

* Título: Decision Trees - Previsão Recém Nascidos

### Relatório do Projeto

Link no [meu Github](<https://lucasfranz.github.io/MLRTemplate/>) *Pages*: [Projeto 4](projetos/Trabalho_4_-_Previsão_recem_nascidos_com_baixo_peso.html)

## Projeto 5

* Título: Regressão Logística - Previsão Recém Nascidos

### Relatório do Projeto

Link no [meu Github](<https://github.com/Efsilvaa>) *Pages*: [Projeto 5](projetos/Trabalho_5_-_previsão_recem_nascidos_por_regressão_Logística.html)

## Projeto 6

* Título: Knn Vinhos

### Relatório do Projeto

Link no [meu Github](<https://lucasfranz.github.io/MLRTemplate/>) *Pages*: [Projeto 6](projetos/trabalho_6_-_KNN_vinhos.html)
